name: Generate Datas

on:
  schedule:
    - cron: '0 */12 * * *'  # Execute every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake animation for contribution graph
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: roman1618
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
